version: '3.8'

services:
  agents:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "54367:54367"
    environment:
      - NODE_ENV=development
    env_file:
      - ../../.env
    volumes:
      # Mount source code for development
      - ./src:/app/src
      - ./templates:/app/templates
      - ./resources:/app/resources
      - ../../langgraph.json:/app/langgraph.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54367/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  agents-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "54367:54367"
    environment:
      - NODE_ENV=production
    env_file:
      - ../../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54367/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: opencanvas-agents
